language: go

go:
  - 1.7
  - 1.8
  - tip

install:
  - go get -u github.com/golang/lint/golint

script:
  - make vet
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
